In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np

In [3]:
iris = load_iris()

In [4]:
iris.data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4)

In [7]:
X_train.shape

(90, 4)

In [8]:
X_test.shape

(60, 4)

#### Algorithm

In [34]:
k = 10

In [35]:
num_train = X_train.shape[0]
num_test = X_test.shape[0]
dists = np.zeros((num_test, num_train))

In [36]:
dists

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [37]:
for cur_tst in range(num_test):
    for cur_trn in range(num_train):
        diff = X_test[cur_tst, :] - X_train[cur_trn, :]
        dists[cur_tst, cur_trn] =  np.sqrt(diff.dot(diff))

In [38]:
dists

array([[ 1.        ,  3.49428104,  0.97467943, ...,  1.96723156,
         1.17898261,  1.75783958],
       [ 4.56836951,  0.52915026,  4.39772669, ...,  5.3591044 ,
         4.73075047,  5.17300686],
       [ 1.56524758,  5.69736781,  1.37840488, ...,  0.81240384,
         1.42828569,  0.70710678],
       ..., 
       [ 4.59129611,  1.04403065,  4.36692111, ...,  5.28677596,
         4.72757866,  5.1273775 ],
       [ 0.80622577,  4.99199359,  0.64807407, ...,  0.66332496,
         0.64807407,  0.4       ],
       [ 0.87177979,  3.8457769 ,  0.7       , ...,  1.7691806 ,
         0.94339811,  1.396424  ]])

In [39]:
preds = np.zeros(num_test)

In [40]:
for i in range(num_test):
    closest_idx = np.argsort(dists[i, :])[:k].tolist()
    closest_y = y_train[closest_idx]
    
    counts = np.bincount(closest_y)
    preds[i] = np.argmax(counts)

In [41]:
preds

array([ 1.,  0.,  2.,  0.,  2.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
        0.,  2.,  2.,  2.,  1.,  2.,  2.,  2.,  0.,  2.,  0.,  0.,  2.,
        0.,  1.,  0.,  1.,  1.,  1.,  0.,  2.,  0.,  2.,  2.,  2.,  2.,
        1.,  0.,  1.,  2.,  0.,  2.,  1.,  2.,  1.,  1.,  0.,  0.,  0.,
        0.,  2.,  0.,  2.,  1.,  0.,  2.,  1.])

In [42]:
from sklearn.metrics import confusion_matrix

In [43]:
# k = 10
confusion_matrix(y_test, preds)

array([[20,  0,  0],
       [ 0, 15,  1],
       [ 0,  4, 20]])

In [23]:
# k = 5
confusion_matrix(y_test, preds)

array([[20,  0,  0],
       [ 0, 15,  1],
       [ 0,  1, 23]])